// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package datahandling

import ()

type Product struct {
	ID         int32
	Details    string
	Name       string
	Price      float64
	CategoryID int32
}
